# Matrizes Multidimensionais com Numpy

In [2]:
import numpy as np

## Vetor 

In [4]:
matriz = np.array([1, 2, 4, 5])
matriz

array([1, 2, 4, 5])

In [42]:
matriz[1]

2

In [41]:
matriz.shape

(4,)

### Acessando os Elementos de uma Matriz 1D (Vetor)

In [24]:
for i in matriz:
    print(i, end=" ")

1 2 4 5 

## Matriz 2D

In [44]:
matriz_2d = np.array([[1, 2, 3, 4], [4, 3, 2, 1]])
matriz_2d

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [45]:
matriz_2d.shape

(2, 4)

### Acessando os Elementos de uma Matriz 2D

In [46]:
matriz_2d[0][0]

1

In [47]:
matriz_2d[1][3]

1

In [49]:
for i in matriz_2d:
    for j in i:
        if (j > 2):
            print(j, end=" ")
    print("\n")
print("fim")

3 4 

4 3 

fim


## Matriz 3D

In [33]:
matriz_3d = np.array([ [[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]] ])
matriz_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [50]:
matriz_3d.shape

(2, 2, 3)

### Acessando os Elementos de uma Matriz 3D

In [51]:
matriz_3d[0][1][0]

4

In [52]:
matriz_3d[1][1][2]

12

In [55]:
for i in matriz_3d:
    for j in i:
        for n in j:
            print(n, end=" ")
        print("\n")
    print("\n\n")

    

1 2 3 

4 5 6 




7 8 9 

10 11 12 




