# Operadores Aritméticos Aplicados a Matrizes Numpy

### Importando a Biblioteca Numpy

In [1]:
import numpy as np

### Crindo as Matrizes 

In [25]:
vetor = np.array([2, 3, 4])
vetor

array([2, 3, 4])

### Aplicando Operações Aritméticas em um Vetor Numpy

#### Soma

In [28]:
vetor + 2

array([4, 5, 6])

#### Subtração

In [29]:
vetor - 2

array([0, 1, 2])

#### Divisão

In [30]:
vetor / 2

array([1. , 1.5, 2. ])

#### Multplicação

In [31]:
vetor * 2

array([4, 6, 8])

#### Potenciação

In [32]:
vetor ** 2

array([ 4,  9, 16])

### Aplicando Operações Aritméticas em um Matriz 2D Numpy

In [33]:
matriz_2d = np.array([[1, 2, 3], [4, 5, 6], [4, 5, 6]])
matriz_2d 

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

#### Soma

In [34]:
matriz_2d + 2

array([[3, 4, 5],
       [6, 7, 8],
       [6, 7, 8]])

#### Subtração

In [35]:
matriz_2d - 2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 2,  3,  4]])

#### Divisão

In [36]:
matriz_2d / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [2. , 2.5, 3. ]])

#### Multplicação

In [37]:
matriz_2d * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [ 8, 10, 12]])

#### Potenciação

In [38]:
matriz_2d ** 2

array([[ 1,  4,  9],
       [16, 25, 36],
       [16, 25, 36]])