# Operações Aritméticos Entre Matrizes Numpy

#### Importando a Biblioteca Numpy

In [1]:
import numpy as np

<br>

---

## Operações Aritméticos Entre Matrizes Unidimensionais

#### Criando os vetores para exemplificar

In [27]:
vetor1 = np.array([1, 2, 3, 4])
vetor2 = np.array([1, 2, 3, 4])

print(f"vetor1: {vetor1}")
print(f"vetor2: {vetor2}")

vetor1: [1 2 3 4]
vetor2: [1 2 3 4]


<br>

---
- #####  Soma Entre Matrizes Unidimensionais

In [28]:
vetor1 + vetor2

array([2, 4, 6, 8])

In [45]:
vetor1 + vetor2 + vetor2

array([ 3,  6,  9, 12])

<br>

---
- ##### Subtração Entre Matrizes Unidimensionais

In [29]:
vetor1 - vetor2

array([0, 0, 0, 0])

In [47]:
vetor1 - vetor2 - vetor2

array([-1, -2, -3, -4])

<br>

---
- ##### Divisão Entre Matrizes Unidimensionais

In [30]:
vetor1 / vetor2

array([1., 1., 1., 1.])

In [48]:
vetor1 / vetor2 / vetor2

array([1.        , 0.5       , 0.33333333, 0.25      ])

<br>

---
- ##### Multplicação Entre Matrizes Unidimensionais

In [23]:
vetor1 * vetor2

array([ 1,  4,  9, 16])

In [49]:
vetor1 * vetor2 * vetor2

array([ 1,  8, 27, 64])

<br>

---
- ##### Potenciação Entre Matrizes Unidimensionais

In [24]:
vetor2 ** vetor1

array([  1,   4,  27, 256])

In [50]:
vetor1 ** vetor2 ** vetor2

array([            1,            16, 7625597484987,             0])

In [51]:
vetor1 * vetor2 / vetor2 + vetor2 - vetor1 ** vetor2

array([   1.,    0.,  -21., -248.])

<br>

---

## Operações Aritméticos Entre Matrizes Multidimensionais

#### Criando as Matrizes para Exemplificar

In [33]:
matriz1_2d = np.array([[1, 2, 3], [1, 2, 3]])
matriz2_2d = np.array([[1, 2, 3], [1, 2, 3]])

print(f"Matriz 1 2D: \n{matriz1_2d}\n")
print(f"Matriz 2 2D: \n{matriz2_2d}")

Matriz 1 2D: 
[[1 2 3]
 [1 2 3]]

Matriz 2 2D: 
[[1 2 3]
 [1 2 3]]


<br>

---
- #####  Soma Entre Matrizes Unidimensionais

In [34]:
matriz1_2d + matriz2_2d

array([[2, 4, 6],
       [2, 4, 6]])

<br>

---
- #####  Subtração Entre Matrizes Unidimensionais

In [35]:
matriz1_2d - matriz2_2d

array([[0, 0, 0],
       [0, 0, 0]])

<br>

---
- #####  Divisão Entre Matrizes Unidimensionais

In [37]:
matriz1_2d / matriz2_2d

array([[1., 1., 1.],
       [1., 1., 1.]])

<br>

---
- #####  Multplicação Entre Matrizes Unidimensionais

In [38]:
matriz1_2d * matriz2_2d

array([[1, 4, 9],
       [1, 4, 9]])

<br>

---
- #####  Potenciação Entre Matrizes Unidimensionais

In [41]:
matriz1_2d ** matriz2_2d

array([[ 1,  4, 27],
       [ 1,  4, 27]])

In [52]:
matriz1_2d + matriz2_2d * matriz1_2d ** matriz1_2d / matriz1_2d

array([[ 2.,  6., 30.],
       [ 2.,  6., 30.]])