# <center> Produto  Escalar Entre Matrizes com NumPy</center> 


#### Importando a Biblioteca NumPy

In [1]:
import numpy as np

<br>

## Produto  Escalar

> O Produto Escalar, ou Produto Interno é a multiplicação de uma matriz pela outra, porém essa multiplicação entre as matrizes não seguem o mesmo processo de uma multiplicação de matriz por um escalar.

> Para podermos executar um produto escalar entre matrizes, devemos observar o seguinte critério.
>> + O número de colunas da primeira matriz deve ser igual ao número de linhas da segunda matriz.

##### Exemplo:

![test](rasculhos_codes_etc/prod_dot.png)

### Caso Unidimensionais

 - ##### Criando as matrizes  (vetores)

In [8]:
vetor1 = np.array([1, 2, 3])
vetor2 = np.array([2, 1, 6])

print(f"vetor 1: {vetor1}")
print(f"vetor 2: {vetor2}")

vetor 1: [1 2 3]
vetor 2: [2 1 6]


#### Encontrando o Produto Escalar com o Método np.dot() do NumPy

In [9]:
vetor3 = np.dot(vetor1, vetor2)
print(f"Vetor 3: {vetor3}")

Vetor 3: 22


<br>

### Caso Multidimensional

- #####  Criando as matrizes 2D

In [23]:
m1 = np.array([[3, 1, 2], [2, 3, 5]])
m2 = np.array([[3, 1, 2], [2, 3, 5], [5, 2, 3]])

print(f"m 1:\n {m1}\n")
print(f"m 2:\n {m2}")

m 1:
 [[3 1 2]
 [2 3 5]]

m 2:
 [[3 1 2]
 [2 3 5]
 [5 2 3]]


#### Encontrando o Produto Escalar com o Método np.dot() do NumPy

In [24]:
m3 = np.dot(m1, m2)
print(f"m 3:\n {m3}")

m 3:
 [[21 10 17]
 [37 21 34]]
